name: Test

on:
  push:
    branches:
     - 2023-Apr-24_PR-Automated-Linting
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Pull Request Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.3
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        python -m venv testenv
        source testenv/bin/activate
        pip install -r requirements.txt
        pip install pylint
    - name: Run Pylint
      run: |
        pylint s3_bucket_cleaner.py
